In [2]:
import pandas as pd
import numpy as np

In [4]:
cd = pd.read_csv('owid-covid-data.csv')

In [5]:
cd.head()

iso_code continent     location        date  total_cases  new_cases  \
0      AFG      Asia  Afghanistan  2020-02-24          5.0        5.0   
1      AFG      Asia  Afghanistan  2020-02-25          5.0        0.0   
2      AFG      Asia  Afghanistan  2020-02-26          5.0        0.0   
3      AFG      Asia  Afghanistan  2020-02-27          5.0        0.0   
4      AFG      Asia  Afghanistan  2020-02-28          5.0        0.0   

   new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  ...  \
0                 NaN           NaN         NaN                  NaN  ...   
1                 NaN           NaN         NaN                  NaN  ...   
2                 NaN           NaN         NaN                  NaN  ...   
3                 NaN           NaN         NaN                  NaN  ...   
4                 NaN           NaN         NaN                  NaN  ...   

   female_smokers  male_smokers  handwashing_facilities  \
0             NaN           NaN                  37.746   
1             NaN           NaN                  37.746   
2             NaN           NaN                  37.746   
3             NaN           NaN                  37.746   
4             NaN           NaN                  37.746   

   hospital_beds_per_thousand  life_expectancy  human_development_index  \
0                         0.5            64.83                    0.511   
1                         0.5            64.83                    0.511   
2                         0.5            64.83                    0.511   
3                         0.5            64.83                    0.511   
4                         0.5            64.83                    0.511   

   excess_mortality_cumulative_absolute  excess_mortality_cumulative  \
0                                   NaN                          NaN   
1                                   NaN                          NaN   
2                                   NaN                          NaN   
3                                   NaN                          NaN   
4                                   NaN                          NaN   

   excess_mortality  excess_mortality_cumulative_per_million  
0               NaN                                      NaN  
1               NaN                                      NaN  
2               NaN                                      NaN  
3               NaN                                      NaN  
4               NaN                                      NaN  

[5 rows x 67 columns]

In [7]:
cd['new_cases'].to_numpy()

array([  5.,   0.,   0., ..., 553.,   0., 441.])

In [8]:
cd.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'new_tests', 'total_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       't

In [9]:
cd.index

RangeIndex(start=0, stop=155139, step=1)

In [10]:
cd.values

array([['AFG', 'Asia', 'Afghanistan', ..., nan, nan, nan],
       ['AFG', 'Asia', 'Afghanistan', ..., nan, nan, nan],
       ['AFG', 'Asia', 'Afghanistan', ..., nan, nan, nan],
       ...,
       ['ZWE', 'Africa', 'Zimbabwe', ..., nan, nan, nan],
       ['ZWE', 'Africa', 'Zimbabwe', ..., nan, nan, nan],
       ['ZWE', 'Africa', 'Zimbabwe', ..., nan, nan, nan]], dtype=object)

In [11]:
cd['new_cases'].count()

152239

In [12]:
cd['new_cases'].min()

-74347.0

In [13]:
cd['new_cases'].max()

3701643.0

In [14]:
cd['new_cases'].unique()

array([5.000e+00, 0.000e+00, 3.000e+00, ..., 4.872e+03, 3.406e+03,
       4.180e+03])

In [15]:
cd['new_cases'].value_counts()

0.0         37468
1.0          3684
2.0          2438
3.0          1970
4.0          1657
            ...  
21095.0         1
10698.0         1
117145.0        1
21182.0         1
28033.0         1
Name: new_cases, Length: 19601, dtype: int64

In [16]:
cd['new_cases'].describe()

count    1.522390e+05
mean     9.063711e+03
std      5.943285e+04
min     -7.434700e+04
25%      1.000000e+00
50%      7.200000e+01
75%      9.470000e+02
max      3.701643e+06
Name: new_cases, dtype: float64

In [18]:
cd['new_cases'].values

array([  5.,   0.,   0., ..., 553.,   0., 441.])

In [19]:
cd[['date','new_cases']]

date  new_cases
0       2020-02-24        5.0
1       2020-02-25        0.0
2       2020-02-26        0.0
3       2020-02-27        0.0
4       2020-02-28        0.0
...            ...        ...
155134  2022-01-12     1433.0
155135  2022-01-13      651.0
155136  2022-01-14      553.0
155137  2022-01-15        0.0
155138  2022-01-16      441.0

[155139 rows x 2 columns]

In [21]:
cd.iloc[1:10,5]

1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
6    0.0
7    0.0
8    0.0
9    0.0
Name: new_cases, dtype: float64

In [22]:
cd.loc[20:30,'date']

20    2020-03-15
21    2020-03-16
22    2020-03-17
23    2020-03-18
24    2020-03-19
25    2020-03-20
26    2020-03-21
27    2020-03-22
28    2020-03-23
29    2020-03-24
30    2020-03-25
Name: date, dtype: object

In [23]:
cd.dtypes

iso_code                                    object
continent                                   object
location                                    object
date                                        object
total_cases                                float64
                                            ...   
human_development_index                    float64
excess_mortality_cumulative_absolute       float64
excess_mortality_cumulative                float64
excess_mortality                           float64
excess_mortality_cumulative_per_million    float64
Length: 67, dtype: object

In [27]:
cd['date'] = cd['date'].astype('datetime64')

In [28]:
cd['date'].dt.day

0         24
1         25
2         26
3         27
4         28
          ..
155134    12
155135    13
155136    14
155137    15
155138    16
Name: date, Length: 155139, dtype: int64

In [30]:
cd['date'].dt.month

0         2
1         2
2         2
3         2
4         2
         ..
155134    1
155135    1
155136    1
155137    1
155138    1
Name: date, Length: 155139, dtype: int64

In [31]:
cd = pd.read_csv('owid-covid-data.csv', parse_dates = ['date'])

In [32]:
cd['date']

0        2020-02-24
1        2020-02-25
2        2020-02-26
3        2020-02-27
4        2020-02-28
            ...    
155134   2022-01-12
155135   2022-01-13
155136   2022-01-14
155137   2022-01-15
155138   2022-01-16
Name: date, Length: 155139, dtype: datetime64[ns]

In [34]:
cd['total_deaths'].isna().sum()

20140

In [36]:
cd['total_deaths'].fillna(-158)

0         -158.0
1         -158.0
2         -158.0
3         -158.0
4         -158.0
           ...  
155134    5215.0
155135    5222.0
155136    5238.0
155137    5238.0
155138    5247.0
Name: total_deaths, Length: 155139, dtype: float64

In [37]:
'Poland' in cd['location'].unique()

True

In [38]:
cd.loc[cd['location'] == 'Poland']

iso_code continent location       date  total_cases  new_cases  \
112698      POL    Europe   Poland 2020-03-04          1.0        1.0   
112699      POL    Europe   Poland 2020-03-05          1.0        0.0   
112700      POL    Europe   Poland 2020-03-06          5.0        4.0   
112701      POL    Europe   Poland 2020-03-07          5.0        0.0   
112702      POL    Europe   Poland 2020-03-08         11.0        6.0   
...         ...       ...      ...        ...          ...        ...   
113377      POL    Europe   Poland 2022-01-12    4248559.0    16173.0   
113378      POL    Europe   Poland 2022-01-13    4265433.0    16874.0   
113379      POL    Europe   Poland 2022-01-14    4281482.0    16049.0   
113380      POL    Europe   Poland 2022-01-15    4298375.0    16893.0   
113381      POL    Europe   Poland 2022-01-16    4313036.0    14661.0   

        new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  \
112698                 NaN           NaN         NaN                  NaN   
112699                 NaN           NaN         NaN                  NaN   
112700                 NaN           NaN         NaN                  NaN   
112701                 NaN           NaN         NaN                  NaN   
112702                 NaN           NaN         NaN                  NaN   
...                    ...           ...         ...                  ...   
113377           12263.429      100938.0       684.0              324.571   
113378           12305.857      101419.0       481.0              301.143   
113379           12898.429      101841.0       422.0              344.714   
113380           13755.000      102270.0       429.0              364.286   
113381           14262.714      102305.0        35.0              366.143   

        ...  female_smokers  male_smokers  handwashing_facilities  \
112698  ...            23.3          33.1                     NaN   
112699  ...            23.3          33.1                     NaN   
112700  ...            23.3          33.1                     NaN   
112701  ...            23.3          33.1                     NaN   
112702  ...            23.3          33.1                     NaN   
...     ...             ...           ...                     ...   
113377  ...            23.3          33.1                     NaN   
113378  ...            23.3          33.1                     NaN   
113379  ...            23.3          33.1                     NaN   
113380  ...            23.3          33.1                     NaN   
113381  ...            23.3          33.1                     NaN   

        hospital_beds_per_thousand  life_expectancy  human_development_index  \
112698                        6.62            78.73                     0.88   
112699                        6.62            78.73                     0.88   
112700                        6.62            78.73                     0.88   
112701                        6.62            78.73                     0.88   
112702                        6.62            78.73                     0.88   
...                            ...              ...                      ...   
113377                        6.62            78.73                     0.88   
113378                        6.62            78.73                     0.88   
113379                        6.62            78.73                     0.88   
113380                        6.62            78.73                     0.88   
113381                        6.62            78.73                     0.88   

        excess_mortality_cumulative_absolute  excess_mortality_cumulative  \
112698                                   NaN                          NaN   
112699                                   NaN                          NaN   
112700                                   NaN                          NaN   
112701                                   NaN                          NaN   
112702                        

In [41]:
cd.groupby('location').agg(sum_cases=('new_cases',np.sum))

sum_cases
location                      
Afghanistan           158717.0
Africa              10325649.0
Albania               232637.0
Algeria               226057.0
Andorra                29888.0
...                        ...
Wallis and Futuna        454.0
World              327500170.0
Yemen                  10252.0
Zambia                296132.0
Zimbabwe              226078.0

[238 rows x 1 columns]